config/routes.rb
Rails.application.routes.draw do
  devise_for :users


    root 'posts#index'



  resources :posts do
    resources :tags
  end


  resources :tags do
    resources :posts
  end



end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags

  validates :author, :presence => true,
                    :length => {:maximum => 30}
  validates :title, :presence => true,
                    :length => {:maximum => 100}
  validates :body,   :presence => true


  mount_uploader :picture, PictureUploader
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates :name, :presence => true,
                   :length => {:maximum => 20}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

    protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]
  before_action :set_default, only: [ :show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @tags = Tag.all
    @tag = Tag.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Your post was added"
      redirect_to post_path(@post)
    else
      flash[:danger] = "Oops, something went wrong and your post wasn't saved"
      redirect_to :back
    end
  end

  def show
    @tags = @post.tags

  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post change saved"
      redirect_to post_path(@post)
    else
      flash[:danger] = "Nope, nothing has changed."
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post deleted."
      redirect_to posts_path
    else
      flash[:danger] = "Post is still there, try again."
      redirect_to post_path(@post)
    end
  end




  private

  def set_default
    @posts = Post.all
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:author, :title, :body, :picture, :tag_ids => [])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]

  def index
  end

  def new
    @tag = Tag.new

  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "New tag added."
      redirect_to posts_path
    else
      flash[:danger] = "Oops, try again"
      redirect_to posts_path
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts

  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_flash.html.erb
<div id="flash-container" class="text-center">
  <% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Blog", posts_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? && current_user.admin? %>
        <li><%= link_to "Add Post", new_post_path %> </li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %> </li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %> </li>
        <li><%= link_to "Sign Up", new_user_registration_path %> </li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<%= render 'layouts/flash' %>

<%= yield %>
<%= debug(params) if Rails.env.devopement? %>
</body>
</html>

app/views/posts/_form.html.erb
<%= render 'layouts/errors', :object => @post %>

<div class="container">
  <%= form_for [@post], html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :title%>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body%>
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :picture%>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
    <div class="form-group">
      <%= f.label "Add tags to this post" %>
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name  %>
    </div>

    <%= f.submit "Add post", class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/posts/edit.html.erb
<h2> Edit <%= @post.title %> </h2>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <% if @posts.any? %>
        <h2>Recent Posts:</h2>
        <ul>
          <% @posts.each do |post| %>
            <div class="row post-tile">

                <div class="col-sm-3 post-image">
                  <li><%= image_tag post.picture.url(:thumb) %>
                </div>

                <div class="col-m-9 post-text">
                    <%= link_to post_path(post) do %>
                    <h3><%= post.title %></h3>
                  <%= truncate post.body, length: 160 %></li>
                  <% end %>
                </div>
            </div>
          <% end %>
        </ul>
      <% else %>
      <h3>No posts yet!</h3>
      <%end  %>
    </div>

    <div class="col-md-4">

      <% if user_signed_in? && current_user.admin? %>
          <%= render "/tags/form" %>
      <% end %>

      <% if @tags.any? %>
        <ul>
          <h3>Tags:</h3>
          <% @tags.each do |tag| %>
            <li> <%= link_to tag.name, tag_path(tag) %> </li>
          <% end %>
        </ul>
      <% end %>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="col-md-8">


    <h2> <%= @post.title %></h2>
    <%= link_to "Edit", edit_post_path(@post) %> |
    <%= link_to "Delete", post_path(@post), :method => "delete" %>

    <%= image_tag @post.picture.url %>
    <%= @post.user.email %>
    <h3> <%= @post.author %> </h3>

    <h3><%= @post.created_at.strftime("%B %d, %Y ")%></h3>

    <p> <%= @post.body %></p>

    <% if @tags.any? %>
    <h3>Tags:</h3>
    <ul>
      <% @tags.each do |tag| %>
        <li> <%= link_to tag.name, tag_path(tag) %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
</div>

app/views/tags/_form.html.erb
<%= render 'layouts/errors', :object => @tag %>

<%= form_for @tag do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name  %>
  <%= f.submit "Add a tag" %>
<% end %>

app/views/tags/show.html.erb
<h2>Posts about <%= @tag.name %> </h2>
<% if @posts.any? %>
<ul>
  <% @posts.each do |post| %>
    <li> <%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>
<% else %>
<h4>No posts yet!</h4>
<% end %>